spring:
  #热部署，先要改settings的compiler，再改shift+ctrl+alt+/的compiler
  devtools:
    restart:
      #需要实时更新的路径
      additional-paths: resources/**,static/**,templates/**,*/**
  resources:
    static-locations: classpath:static/,file:${spring.servlet.multipart.location}
  aop:
    auto: true
  datasource:
    # 连接池指定 springboot2.02版本默认使用HikariCP 此处要替换成Druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://47.98.59.73:12345/testsystem?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: my-secret-pw
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 是否缓存preparedStatement
    # 打开PSCache，并且指定每个连接上PSCache的大小。官方建议MySQL下建议关闭，如果用SQL防火墙建议打开
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #  上传文件大小
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100000000
      max-request-size: 100000000

mybatis:
  type-aliases-package: com.happyfamily.springboot.crowdsourcingplatform.model
  mapper-locations: classpath:/mybatis-mappers/**
  configuration:
    mapUnderscoreToCamelCase: true

#logging:
#  file:
#    path: D:\MyProject\myfourseason

#对应apicontroller
api-url-front: /api-front
api-url-back: /api-back

server:
  port: 8080

#爬虫相关路径
worm:
  #互联网动态
  url: http://it.sohu.com/911?spm=smpc.ch30.top-subnav.2.1582114678013lQLIwp9
